title: Song Li
description: 读书、编程、思考
url: "https://sbookworm.github.io"
github: "https://github.com/sbookworm"

remote_theme: chirpy/jekyll-theme-chirpy
timezone: Asia/Shanghai

permalink: /:title/

jekyll_opts:
  - --quiet
