# Chirpy Theme
theme: jekyll-theme-chirpy

lang: zh-CN
timezone: Asia/Shanghai

title: Song Li
tagline: 读书、编程、思考
description: 个人博客

url: "https://sbookworm.github.io"
github:
  username: sbookworm

social:
  name: Song Li
  email: sbookworm@gmail.com
  links:
    - https://github.com/sbookworm

avatar: /commons/avatar.jpg

theme_mode: dark

# 简化配置
comments:
  provider:
